export const CONSTANTS = {
    COMPANY: {},
    DATE: {
        RANGE: ["Last Day", "Last Week", "Last Month", "Last Year"],
    },
    JOB: {
        STATUS: ["Active", "Hidden"],
        EXPERIENCES: [
            "Full-time",
            "Part-time",
            "Internship",
            "Contract",
            "Freelance",
        ],
        INDUSTRIES: [
            "Aerospace",
            "Agriculture",
            "Aquaculture",
            "Architecture",
            "Artificial Intelligence",
            "Automated Manufacturing",
            "Automotive",
            "Banking and Finance",
            "Biotechnology",
            "Blockchain Technology",
            "Catering",
            "Chemical",
            "Clean Energy",
            "Cloud Computing",
            "Construction",
            "Cybersecurity",
            "Digital Marketing",
            "E-commerce",
            "Economic Development",
            "Education",
            "Elder Care",
            "Electronics",
            "Energy",
            "Entertainment",
            "Environmental",
            "Fashion",
            "Fitness and Wellness",
            "Food and Beverage",
            "Forestry",
            "Gaming",
            "Government",
            "Green Technology",
            "Healthcare",
            "Hospitality",
            "Human Resources",
            "Information Technology",
            "Insurance",
            "Interior Design",
            "Internet of Things (IoT)",
            "Legal Services",
            "Logistics",
            "Manufacturing",
            "Maritime Industry",
            "Marketing and Advertising",
            "Media and Communications",
            "Mobile Technology",
            "Music Industry",
            "Nanotechnology",
            "Nonprofit",
            "Pharmaceutical",
            "Printing",
            "Professional Services",
            "Real Estate",
            "Renewable Energy",
            "Retail",
            "Robotics",
            "Space Exploration",
            "Sports Management",
            "Sustainable Development",
            "Telecommunications",
            "Textile",
            "Tourism",
            "Transportation and Logistics",
            "Virtual Reality",
            "Waste Management",
            "Water Industry",
            "Wearable Technology",
            "Wildlife Conservation",
        ],
    },
    ORDER: ["Newest", "Oldest", "Highest Salary", "Lowest Salary"],
    PRINCIPAL: {
        ANONYMOUS: "2vxsx-fae",
    },
};
