export const CONSTANTS = {
    COMPANY: {
        COUNTRIES: [
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cabo Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Congo",
            "Costa Rica",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czech Republic",
            "Democratic Republic of the Congo",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "East Timor",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini",
            "Ethiopia",
            "Fiji",
            "Finland",
            "France",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Greece",
            "Grenada",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Ivory Coast",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Kosovo",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Mauritania",
            "Mauritius",
            "Mexico",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "North Korea",
            "North Macedonia",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Palestine",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Qatar",
            "Romania",
            "Russia",
            "Rwanda",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Korea",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Togo",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "United States",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Vatican City",
            "Venezuela",
            "Vietnam",
            "Yemen",
            "Zambia",
            "Zimbabwe",
        ],
    },
    DATE: {
        RANGE: ["Last Day", "Last Week", "Last Month", "Last Year"],
    },
    JOB: {
        STATUS: ["Active", "Hidden"],
        EXPERIENCES: [
            "Full-time",
            "Part-time",
            "Internship",
            "Contract",
            "Freelance",
        ],
        INDUSTRIES: [
            "Aerospace",
            "Agriculture",
            "Aquaculture",
            "Architecture",
            "Artificial Intelligence",
            "Automated Manufacturing",
            "Automotive",
            "Banking and Finance",
            "Biotechnology",
            "Blockchain Technology",
            "Catering",
            "Chemical",
            "Clean Energy",
            "Cloud Computing",
            "Construction",
            "Cybersecurity",
            "Digital Marketing",
            "E-commerce",
            "Economic Development",
            "Education",
            "Elder Care",
            "Electronics",
            "Energy",
            "Entertainment",
            "Environmental",
            "Fashion",
            "Fitness and Wellness",
            "Food and Beverage",
            "Forestry",
            "Gaming",
            "Government",
            "Green Technology",
            "Healthcare",
            "Hospitality",
            "Human Resources",
            "Information Technology",
            "Insurance",
            "Interior Design",
            "Internet of Things (IoT)",
            "Legal Services",
            "Logistics",
            "Manufacturing",
            "Maritime Industry",
            "Marketing and Advertising",
            "Media and Communications",
            "Mobile Technology",
            "Music Industry",
            "Nanotechnology",
            "Nonprofit",
            "Pharmaceutical",
            "Printing",
            "Professional Services",
            "Real Estate",
            "Renewable Energy",
            "Retail",
            "Robotics",
            "Space Exploration",
            "Sports Management",
            "Sustainable Development",
            "Telecommunications",
            "Textile",
            "Tourism",
            "Transportation and Logistics",
            "Virtual Reality",
            "Waste Management",
            "Water Industry",
            "Wearable Technology",
            "Wildlife Conservation",
        ],
    },
    ORDER: ["Newest", "Oldest", "Highest Salary", "Lowest Salary"],
    PRINCIPAL: {
        ANONYMOUS: "2vxsx-fae",
    },
    REVIEWS: {
        CULTURE: [
            "Toxic: Unhealthy environment",
            "Poor: Subpar culture",
            "Average: Room for improvement",
            "Good: Supportive atmosphere",
            "Excellent: Thriving, valued employees",
        ],
        WORKLIFE_BALANCE: [
            "Poor: Bad place to be in",
            "Fair: Could be better",
            "Average: Balances work and personal life",
            "Good: Provides a healthy balance",
            "Excellent: Exceptional work-life balance",
        ],
        SENIOR_MANAGEMENT: [
            "Poor: Disconnected from employees",
            "Fair: Needs improvement in communication",
            "Average: Provides adequate direction",
            "Good: Supportive and communicative",
            "Excellent: Inspiring and effective leadership",
        ],
        RECOMMEND_TO_FRIEND: ["Yes", "No"],
        ORDER_BY: ["Newest", "Oldest", "Highest Rating", "Lowest Rating"],
    },
};
